name: Generate trophies card

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:
      - name: Generate trophies.svg
        uses: ryo-ma/github-profile-trophy@v1
        with:
          username: MedFadl
          token: ${{ secrets.GITHUB_TOKEN }}
          theme: darkhub

      - name: Move output
        run: |
          mkdir -p dist
          mv trophy.svg dist/trophy.svg

      - name: Deploy to trophies-output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: trophies-output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
