name: Generate trophies card

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:
      - name: Create output directory
        run: mkdir -p dist

      # Generate Dark Theme Trophies using cURL
      - name: Fetch dark trophies
        run: curl "https://github-profile-trophy.vercel.app/?username=MedFadl&theme=darkhub&no-bg=true&no-frame=true&row=1&column=7&margin-w=15" -o dist/trophies-dark.svg

      # Generate Light Theme Trophies using cURL
      - name: Fetch light trophies
        run: curl "https://github-profile-trophy.vercel.app/?username=MedFadl&theme=flat&no-bg=true&no-frame=true&row=1&column=7&margin-w=15" -o dist/trophies-light.svg

      # Push both SVGs to the output branch
      - name: Deploy to trophies-output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: trophies-output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
