name: Generate trophies card

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:
      - name: Create output directory
        run: mkdir -p dist

      # Generate Dark Theme Trophies
      - name: Generate trophies-dark.svg
        uses: ryo-ma/github-profile-trophy@master
        with:
          username: MedFadl
          token: ${{ secrets.GITHUB_TOKEN }}
          theme: darkhub
          no-bg: true
          no-frame: true
          row: 1
          column: 7
          margin-w: 15

      - name: Move dark output
        run: mv trophy.svg dist/trophies-dark.svg

      # Generate Light Theme Trophies
      - name: Generate trophies-light.svg
        uses: ryo-ma/github-profile-trophy@master
        with:
          username: MedFadl
          token: ${{ secrets.GITHUB_TOKEN }}
          theme: flat
          no-bg: true
          no-frame: true
          row: 1
          column: 7
          margin-w: 15

      - name: Move light output
        run: mv trophy.svg dist/trophies-light.svg

      # Push both SVGs to the output branch
      - name: Deploy to trophies-output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: trophies-output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
